-- Supabase PostgreSQL Schema for Library Management System
-- Based on Software Requirements Specification (SRS)
-- FR-01: Book Management
-- FR-02: Issue Book
-- FR-03: Return Book
-- FR-04: Student Members
-- FR-05: Due Date Tracking
-- FR-06: Fine Calculation

-- 1. Create Books Table (FR-01)
CREATE TABLE IF NOT EXISTS books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    author TEXT NOT NULL,
    category TEXT NOT NULL,
    copies INTEGER NOT NULL DEFAULT 1 CHECK (copies >= 0),
    status TEXT NOT NULL DEFAULT 'available' CHECK (status IN ('available', 'issued')),
    cover_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Create Members Table (FR-04)
CREATE TABLE IF NOT EXISTS members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    email TEXT,
    department TEXT NOT NULL,
    books_issued INTEGER NOT NULL DEFAULT 0 CHECK (books_issued >= 0),
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'suspended')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. Create Book Issues Table (FR-02, FR-03, FR-05)
CREATE TABLE IF NOT EXISTS book_issues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT REFERENCES books(id) ON DELETE CASCADE NOT NULL,
    member_id BIGINT REFERENCES members(id) ON DELETE CASCADE NOT NULL,
    issue_date DATE NOT NULL DEFAULT CURRENT_DATE,
    due_date DATE NOT NULL,
    return_date DATE,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'due-soon', 'overdue', 'returned')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. Create Fines Table (FR-06)
CREATE TABLE IF NOT EXISTS fines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id BIGINT REFERENCES book_issues(id) ON DELETE SET NULL,
    member_id BIGINT REFERENCES members(id) ON DELETE CASCADE NOT NULL,
    overdue_days INTEGER NOT NULL DEFAULT 0 CHECK (overdue_days >= 0),
    fine_per_day NUMERIC(10, 2) NOT NULL DEFAULT 5.00 CHECK (fine_per_day >= 0),
    total_fine NUMERIC(10, 2) NOT NULL DEFAULT 0.00 CHECK (total_fine >= 0),
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'paid')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create Indexes for fast lookup
CREATE INDEX IF NOT EXISTS idx_books_status ON books(status);
CREATE INDEX IF NOT EXISTS idx_members_member_id ON members(member_id);
CREATE INDEX IF NOT EXISTS idx_book_issues_status ON book_issues(status);
CREATE INDEX IF NOT EXISTS idx_book_issues_member ON book_issues(member_id);
CREATE INDEX IF NOT EXISTS idx_book_issues_book ON book_issues(book_id);
CREATE INDEX IF NOT EXISTS idx_fines_member ON fines(member_id);

-- Enable Row Level Security (RLS)
ALTER TABLE books ENABLE ROW LEVEL SECURITY;
ALTER TABLE members ENABLE ROW LEVEL SECURITY;
ALTER TABLE book_issues ENABLE ROW LEVEL SECURITY;
ALTER TABLE fines ENABLE ROW LEVEL SECURITY;

-- Default permissive policies for API access
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'books' AND policyname = 'Allow public access to books') THEN
        CREATE POLICY "Allow public access to books" ON books FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'members' AND policyname = 'Allow public access to members') THEN
        CREATE POLICY "Allow public access to members" ON members FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'book_issues' AND policyname = 'Allow public access to book_issues') THEN
        CREATE POLICY "Allow public access to book_issues" ON book_issues FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'fines' AND policyname = 'Allow public access to fines') THEN
        CREATE POLICY "Allow public access to fines" ON fines FOR ALL USING (true) WITH CHECK (true);
    END IF;
END
$$;

-- Initial Seed Data Migration (Preserves all existing UI records)
INSERT INTO books (title, author, category, copies, status, cover_url)
VALUES
    ('The Great Gatsby', 'F. Scott Fitzgerald', 'Fiction', 12, 'available', 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=500&q=80'),
    ('Atomic Habits', 'James Clear', 'Self Help', 8, 'issued', 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=500&q=80'),
    ('Think and Grow Rich', 'Napoleon Hill', 'Business', 15, 'available', 'https://images.unsplash.com/photo-1541963463532-d68292c34b19?auto=format&fit=crop&w=500&q=80'),
    ('Rich Dad Poor Dad', 'Robert Kiyosaki', 'Finance', 10, 'available', 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=500&q=80'),
    ('Clean Code', 'Robert C. Martin', 'Computer Science', 5, 'issued', 'https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&w=500&q=80')
ON CONFLICT DO NOTHING;

INSERT INTO members (member_id, name, email, department, books_issued, status)
VALUES
    ('LIB001', 'Rahul Kumar', 'rahul@student.edu', 'Information Technology', 2, 'active'),
    ('LIB002', 'Priya S', 'priya@student.edu', 'Computer Science', 1, 'active'),
    ('LIB003', 'Arjun R', 'arjun@student.edu', 'Electronics', 3, 'active')
ON CONFLICT (member_id) DO NOTHING;

-- Seed initial issues linking to books and members
INSERT INTO book_issues (book_id, member_id, issue_date, due_date, status)
SELECT b.id, m.id, '2026-08-25'::date, '2026-09-08'::date, 'active'
FROM books b, members m
WHERE b.title = 'Clean Code' AND m.member_id = 'LIB001'
ON CONFLICT DO NOTHING;

INSERT INTO book_issues (book_id, member_id, issue_date, due_date, status)
SELECT b.id, m.id, '2026-08-20'::date, '2026-09-03'::date, 'due-soon'
FROM books b, members m
WHERE b.title = 'Atomic Habits' AND m.member_id = 'LIB002'
ON CONFLICT DO NOTHING;

INSERT INTO book_issues (book_id, member_id, issue_date, due_date, status)
SELECT b.id, m.id, '2026-08-10'::date, '2026-08-24'::date, 'overdue'
FROM books b, members m
WHERE b.title = 'Rich Dad Poor Dad' AND m.member_id = 'LIB003'
ON CONFLICT DO NOTHING;

INSERT INTO fines (issue_id, member_id, overdue_days, fine_per_day, total_fine, status)
SELECT bi.id, bi.member_id, 28, 5.00, 140.00, 'pending'
FROM book_issues bi
JOIN books b ON bi.book_id = b.id
WHERE b.title = 'Rich Dad Poor Dad'
LIMIT 1
ON CONFLICT DO NOTHING;
